### ISSUE TITLE
Add OAuth popup feature.

### ISSUE THREAD

**Issue by thuonghd3** [sidharthancr/react-popout-v2#2]
Like package. 
https://www.npmjs.com/package/react-oauth-popup

**Comment by sidharthancr** [comment]
The v2 component supports us to get the instance of new opened window in **onCreate** callback, using this you can get the _URL and Params_.

Give the **onCreate** callback once and let me know if it does not work.

@thuonghd3 still, you need the feature, Could you please brief more on it?

**Comment by thuonghd3** [comment]
Ok. Let me check.

**Comment by sidharthancr** [comment]
Since there is no update, closed the issue.
